version: "3"

services:
  api:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: mix phx.server
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: cross_commerce_desafio_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cross_commerce_desafio_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports: 
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: